#!/bin/bash

#### courtesy Linux Journal http://www.linuxjournal.com/node/1005818

cd payload
tar cf ../payload.tar ./*
cd ..

if [ -e "payload.tar" ]; then
    gzip payload.tar

    if [ -e "payload.tar.gz" ]; then
        cat decompress payload.tar.gz > iottlyagentinstaller.bsx
    else
        echo "payload.tar.gz does not exist"
        exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1
fi

rm payload.tar.gz

echo "iottlyagentinstaller.bsx created"
exit 0