#!/bin/bash

#### courtesy Linux Journal http://www.linuxjournal.com/node/1005818

echo ""
echo "Self Extracting Installer"
echo ""

export TMPDIR=`mktemp -d /tmp/iottlyagentinstaller.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR
echo $ARCHIVE
CDIR=`pwd`
cd $TMPDIR
./installer

cd $CDIR
rm -rf $TMPDIR

exit 0

#be sure there is an extra empty line after this one:
__ARCHIVE_BELOW__
